version: "3.4"
services:
  web:
      build: .
      environment:
        SLACK_ENTRYPOINT: ${SLACK_ENTRYPOINT}
        TARGET_CHANNEL: ${TARGET_CHANNEL}
        USER_NAME: ${USER_NAME}
        ICON_URL: ${ICON_URL}
        TEST_USER_NAME: ${TEST_USER_NAME}
        TEST_ICON_URL: ${TEST_ICON_URL}
